### ISSUE TITLE
Specify shift right.

### ISSUE THREAD

**Issue by moonpatroller** [mystborn/GmSharp#2]
Does it carry the sign bit?

**Comment by mystborn** [comment]
No. It uses the basic c# implementation. For example:
```cs
var i = -8;
var j = i >> 2;
show_debug_message(j);

// Outputs:
// -2
```

**Comment by moonpatroller** [comment]
It remaining negative makes me think it is extending the sign bit.  I mentioned it because you might want to say it in the docs.  Sorry, should have said extend not carry.

**Comment by mystborn** [comment]
I've updated the docs :)
